<%! from alembic import op
import sqlalchemy as sa
%>

-- commands auto generated by Alembic - please adjust! --

<% if context.get('upgrade') %>
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
<% endif %>

<% if context.get('downgrade') %>
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
<% endif %>